// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGWWTdQkT8LSPY8WjUQa_-sFl1F9vrgRg',
    appId: '1:801248833040:web:6f114c5b81fa8e4fcae495',
    messagingSenderId: '801248833040',
    projectId: 'foodapp-59c36',
    authDomain: 'foodapp-59c36.firebaseapp.com',
    storageBucket: 'foodapp-59c36.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCadu1gGQpkIN8U9v5w5-h7X8EcxV2ozYE',
    appId: '1:801248833040:android:c4c4a633ade55e03cae495',
    messagingSenderId: '801248833040',
    projectId: 'foodapp-59c36',
    storageBucket: 'foodapp-59c36.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAg0rLzYEyOdslJwBJ7OBa18pK6RlFS2Qc',
    appId: '1:801248833040:ios:fd50a683e0f1d0a3cae495',
    messagingSenderId: '801248833040',
    projectId: 'foodapp-59c36',
    storageBucket: 'foodapp-59c36.appspot.com',
    androidClientId: '801248833040-qhodlk1r4hti8ht09ar8lg3uvlvjs5hu.apps.googleusercontent.com',
    iosClientId: '801248833040-urnvpn27htne8dfr7d3mupc960u2l036.apps.googleusercontent.com',
    iosBundleId: 'com.example.parentalControlApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAg0rLzYEyOdslJwBJ7OBa18pK6RlFS2Qc',
    appId: '1:801248833040:ios:fd50a683e0f1d0a3cae495',
    messagingSenderId: '801248833040',
    projectId: 'foodapp-59c36',
    storageBucket: 'foodapp-59c36.appspot.com',
    androidClientId: '801248833040-qhodlk1r4hti8ht09ar8lg3uvlvjs5hu.apps.googleusercontent.com',
    iosClientId: '801248833040-urnvpn27htne8dfr7d3mupc960u2l036.apps.googleusercontent.com',
    iosBundleId: 'com.example.parentalControlApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-i_KIfI3zMbxdNtjx1ka8YWPEdol81wk',
    appId: '1:801248833040:web:6ce1a86c8c95a514cae495',
    messagingSenderId: '801248833040',
    projectId: 'foodapp-59c36',
    authDomain: 'foodapp-59c36.firebaseapp.com',
    storageBucket: 'foodapp-59c36.appspot.com',
  );
}
